import pyautogui
import time
import keyboard
import pyperclip
import os
import shutil
from openpyxl import load_workbook
import datetime
import glob
import math

#if os.path.isdir('C:/Users/user/Desktop/주차장 만들기'):
    #shutil.rmtree('C:/Users/user/Desktop/주차장 만들기')
APP_DATA = ["FeatureBuilderFloorGenerateWindow","FeatureRebarMaterialWindow","FeatureBuilderStoryMaterialWindow"]
def APP():
    '''
    # 바탕화면에서 빌드허브 실행파일을 찾아서 실행 하기
    file_name = "Chang.NX.NXBuilderStart.exe"
    file_path = "C:/Users/"
    files = glob.glob(file_path + "/**/"+ file_name, recursive= True)
    file_start = files[0]
    os.popen(file_start)
    time.sleep(10)
    '''
    gongs = pyautogui.locateAllOnScreen('E:/park_image/all.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.doubleClick()
    else :
        time.sleep(1)
        gongs = pyautogui.locateAllOnScreen('E:/park_image/all.jpg', confidence=0.99)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.doubleClick()
    time.sleep(2)
    pyautogui.click(25,21) # APP 메뉴 클릭
    time.sleep(0.5)
    pyautogui.click(31, 71) # 새로 만들기 클릭
    time.sleep(2)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/main.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/main.jpg', confidence=0.98)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(2)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/file_name.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/file_name.jpg', confidence=0.88)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    pyautogui.move(100,0)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(1)
    pyperclip.copy('주차장 만들기')
    time.sleep(1)
    pyautogui.hotkey("ctrl","v")
    time.sleep(3)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/save.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    file_name = "주차장 만들기.rhb"
    file_path = "C:/Users/"
    files = glob.glob(file_path + "/**/"+ file_name, recursive= True)
    file_start = 0
    for i in files:
        file_start = i
    print(file_start)
    if os.path.exists(file_start) == True :
        print("ID:2-1-1     테스트요약:새로만들기       결과:PASS")
    else:
        print("ID:2-1-1     테스트요약:새로만들기       결과:FAIL")
        APP()

def FLOOR():
    gongs = pyautogui.locateAllOnScreen('E:/park_image/floor.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/floor.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    pyautogui.doubleClick(866,283)
    pyautogui.hotkey('delete')
    pyautogui.typewrite(['1'])
    time.sleep(1)
    pyautogui.doubleClick(865,307)
    pyautogui.hotkey('delete')
    pyautogui.typewrite(['1'])
    time.sleep(1)
    pyautogui.doubleClick(1190,306)
    pyautogui.hotkey('delete')
    pyautogui.typewrite(['3','9','0','0'])
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/create.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/create.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(2)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/application.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/application.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(2)
    pyautogui.hotkey("esc")

def MATREIAL():
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/material.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/mataerial.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(0.5)
    pyautogui.click(1287,428)
    time.sleep(0.5)
    pyautogui.click(672,535)
    pyautogui.hotkey("delete")
    pyperclip.copy('C27')
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.doubleClick(914,536)
    pyautogui.hotkey("delete")
    pyperclip.copy('27')
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.doubleClick(1198,668)
    pyautogui.hotkey("delete")
    pyperclip.copy('27')
    pyautogui.hotkey("ctrl","v")
    pyautogui.hotkey("esc") 

def MATERIAL_IMAGE():
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/flor_matrerial.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/material.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/suzig.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/suzig.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
    time.sleep(1)
    pyautogui.move(0,20)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(1)
    pyautogui.keyDown("shift")    
    time.sleep(0.5)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/supeoung.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/supeoung.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
    time.sleep(1)
    pyautogui.move(0,50)
    time.sleep(0.5)
    pyautogui.doubleClick()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/c27.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/c27.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    pyautogui.keyUp("shift")
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/supeoung.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/supeoung.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
    time.sleep(1)
    pyautogui.move(0,80)
    time.sleep(1)
    pyautogui.doubleClick()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/C24.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/C24.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/application.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/application.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    pyautogui.hotkey("esc") 

def Sectionin_administar_BUTTRESS():
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/Sectionin_administar.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/Sectionin_administar.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(2)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/buttress.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/buttress.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/insert.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/insert.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/name.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/name.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
    time.sleep(1)
    pyautogui.move(0,80)
    time.sleep(1)
    pyautogui.doubleClick()
    time.sleep(0.5)
    pyautogui.doubleClick()
    pyperclip.copy('BT1')
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    pyperclip.copy('B1F')
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    pyperclip.copy('B1F')
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("enter")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    pyperclip.copy('300')
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    pyperclip.copy('1950')
    pyautogui.hotkey("ctrl","v")
    #상부근
    time.sleep(1)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('2/2-HD19')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.3)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('2/2-HD19')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.3)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('2/2-HD19')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    #하부근
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('2/2-HD19')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('2/2-HD19')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('2/2-HD19')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    #스트럽
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('2-HD10@200')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('2-HD10@200')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('2-HD10@200')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    #측면근,수평전단근
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('HD10@300')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('0-HD10')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/section_application.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/section_application.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)



def Sectionin_administar_DECKSLAVE():
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/slave.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/slave.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/Deck.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/Deck.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/insert.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/insert.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/name.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/name.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
    time.sleep(1)
    pyautogui.move(0,80)
    time.sleep(1)
    pyautogui.doubleClick()
    time.sleep(0.5)
    pyautogui.doubleClick()
    pyperclip.copy('DS11')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("enter")   
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("enter")  
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy('250')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy("HD13@200")
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy("HD13@600")
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("delete")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy("HD13@450")
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy("HD13@450")
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy("HD13@450")
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.3)
    pyperclip.copy("HD13@450")
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/section_application.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/section_application.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)

def Sectionin_administar_RWALL():
    gongs = pyautogui.locateAllOnScreen('E:/park_image/RWALL.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/RWALL.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/insert.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/insert.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/name.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/name.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
    time.sleep(1)
    pyautogui.move(0,80)
    time.sleep(1)
    pyautogui.doubleClick()
    time.sleep(0.5)
    pyautogui.doubleClick()
    pyperclip.copy('DW1')
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("enter")   
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("up")  
    time.sleep(0.5)
    pyautogui.hotkey("enter")  
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("enter")  
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyperclip.copy('300')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("up")  
    time.sleep(0.5)
    pyautogui.hotkey("enter")  
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyperclip.copy('HD13@300')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyperclip.copy('HD16@300-3400')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("enter")  
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyperclip.copy('HD13@300')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyperclip.copy('HD13+16@150')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyperclip.copy('HD13+16@150')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    #전단 보강근 전체 체크
    time.sleep(1)
    pyautogui.click(1259,384)
    time.sleep(1)
    pyautogui.move(75,0)
    time.sleep(0.5)
    pyautogui.doubleClick()
    time.sleep(0.5)
    for i in range(1,10):
        pyautogui.hotkey("delete")
    time.sleep(0.5)
    pyperclip.copy('HD10@200@100')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/bogang_application.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/bogang_application.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(0.5)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/section_application.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/section_application.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)

def Sectionin_administar_ISOFOOT():
    time.sleep(0.5)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/isofoot.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/isofoot.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/insert.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/insert.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/name.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/name.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
    time.sleep(1)
    pyautogui.move(0,80)
    time.sleep(1)
    pyautogui.doubleClick()
    time.sleep(0.5)
    pyautogui.doubleClick()
    pyperclip.copy('PF1')
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")
    time.sleep(0.5)
    pyautogui.hotkey("tab")   
    time.sleep(0.5)
    pyautogui.hotkey("enter")
    time.sleep(0.5)
    pyautogui.hotkey("tab")   
    time.sleep(0.5)
    pyautogui.hotkey("enter")
    time.sleep(0.5)
    pyautogui.hotkey("tab")   
    time.sleep(0.5)
    pyperclip.copy('1250')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")   
    time.sleep(0.5)
    pyperclip.copy('1250')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")   
    time.sleep(0.5)
    pyperclip.copy('600')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")   
    time.sleep(0.5)
    pyperclip.copy('HD19@300')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")   
    time.sleep(0.5)
    pyperclip.copy('HD19@300')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/section_application.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/section_application.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)

def Sectionin_administar_WALLFOOT():
    time.sleep(0.5)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/wallfoot.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/wallfoot.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/insert.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/insert.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/name.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/name.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
    time.sleep(1)
    pyautogui.move(0,80)
    time.sleep(1)
    pyautogui.doubleClick()
    time.sleep(0.5)
    pyautogui.doubleClick()
    pyperclip.copy('WPF1')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab")   
    time.sleep(0.5)
    pyautogui.hotkey("enter")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('2000')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('600')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('HD19@200')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('HD19@300')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('HD13@100')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('HD13@300')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/section_application.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/section_application.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(3)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/close_1.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/close_1.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(0.5)
    pyautogui.hotkey("esc")
   
def EXCEL():
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/EX.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        ongs = pyautogui.locateAllOnScreen('E:/park_image/EX.jpg', confidence=0.95)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    pyautogui.click(293,141)
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/find_1.jpg', confidence=0.93)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        ongs = pyautogui.locateAllOnScreen('E:/park_image/find_1.jpg', confidence=0.99)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/Down.jpg', confidence=0.88)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        ongs = pyautogui.locateAllOnScreen('E:/park_image/Down.jpg', confidence=0.90)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/park_excel.jpg', confidence=0.88)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.doubleClick()
    else :
        ongs = pyautogui.locateAllOnScreen('E:/park_image/park_excel.jpg', confidence=0.90)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.doubleClick()
    time.sleep(1)
    pyautogui.click(1104,541)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/bring.jpg', confidence=0.88)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.doubleClick()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/bring.jpg', confidence=0.90)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.doubleClick()
    time.sleep(7)

def DWGRE():   
    gongs = pyautogui.locateAllOnScreen('E:/park_image/DWG_RE.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :  
        gongs = pyautogui.locateAllOnScreen('E:/park_image/DWG_RE.jpg', confidence=0.88)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.dourbleClick() 
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/add.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :  
        gongs = pyautogui.locateAllOnScreen('E:/park_image/add.jpg', confidence=0.9)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click() 
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/Down.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :  
        gongs = pyautogui.locateAllOnScreen('E:/park_image/Down.jpg', confidence=0.88)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/DO.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.doubleClick()
    else :  
        gongs = pyautogui.locateAllOnScreen('E:/park_image/DO.jpg', confidence=0.)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.doubleClick()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/guzo1.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.doubleClick()
    else :  
        gongs = pyautogui.locateAllOnScreen('E:/park_image/guzo1.jpg', confidence=0.95)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.doubleClick() 
    time.sleep(5)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/PARK_B1F.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.doubleClick()
    else :  
        gongs = pyautogui.locateAllOnScreen('E:/park_image/PARK_B1F.jpg', confidence=0.95)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.doubleClick()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/B1F_1.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click(button='right')
    else :  
        gongs = pyautogui.locateAllOnScreen('E:/park_image/B1F_1.jpg', confidence=0.95)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click(button='right')
    time.sleep(1)
    #참조클립 추가
    pyautogui.click(214,225)
    time.sleep(0.5)
    pyautogui.click(582,990)
    time.sleep(1)
    pyautogui.hotkey('enter')
    time.sleep(1)
    pyautogui.click(556,201)
    time.sleep(1)
    pyautogui.click(1370,773)
    time.sleep(1)
    pyautogui.moveTo(804,454)
    for i in range(1,8):
        pyautogui.scroll(1)
    time.sleep(1)
    pyautogui.click(987,671)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/close.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    time.sleep(3)
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else:
        gongs = pyautogui.locateAllOnScreen('E:/park_image/close.jpg', confidence=0.88)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        time.sleep(1)
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(3)

def B1F_ISOFOOT():
    time.sleep(3)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/B1F_1.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.doubleClick()
    else :
        time.sleep(1)
        gongs = pyautogui.locateAllOnScreen('E:/park_image/B1F_1.jpg', confidence=0.99)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.doubleClick()
    time.sleep(2)
    pyautogui.moveTo(1124,506)
    time.sleep(1)
    for i in range(1,6):
        pyautogui.scroll(1)
    time.sleep(1)
    pyautogui.click(1320,432)
    time.sleep(1)
    pyautogui.click(1312,471)
    time.sleep(1)
    pyautogui.click(436,969)
    time.sleep(0.5)
    pyperclip.copy('li')
    time.sleep(0.5)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("enter")
    time.sleep(1)
    pyautogui.moveTo(1124,506)
    time.sleep(1)
    for i in range(1,6):
        pyautogui.scroll(-1)
    time.sleep(0.5)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/MODELING.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        time.sleep(1)
        gongs = pyautogui.locateAllOnScreen('E:/park_image/MODELING.jpg', confidence=0.99)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/isofoot_model.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        time.sleep(1)
        gongs = pyautogui.locateAllOnScreen('E:/park_image/isofoot_model.jpg', confidence=0.99)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/RECON.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        time.sleep(1)
        gongs = pyautogui.locateAllOnScreen('E:/park_image/RECON.jpg', confidence=0.99)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    pyautogui.doubleClick(622,154)
    time.sleep(1)
    #텍스트 인식거리 입력
    pyperclip.copy('2000')
    time.sleep(0.5)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('3000')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('50')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(1)
    pyautogui.click(798,325)
    time.sleep(1)
    pyautogui.click(1447,716)
    time.sleep(1)
    time.sleep(0.5)
    pyautogui.hotkey("enter")
    time.sleep(1)

def B1F_WALLFOOT():
    k = 0   
    for i in range(1,30):
        time.sleep(2)
        k += 0.1
        gongs = pyautogui.locateAllOnScreen('E:/park_image/sun.jpg', confidence=0.99-k)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
            break
    time.sleep(1)
    pyautogui.moveTo(1302,393)
    time.sleep(1)
    for i in range(1,8):
        pyautogui.scroll(1)
    time.sleep(1)
    pyautogui.click(1316,470)
    time.sleep(1)
    pyautogui.hotkey("esc")
    time.sleep(1)
    pyautogui.click(1335,438)
    time.sleep(1)
    pyautogui.click(1324,444)
    time.sleep(1)
    pyautogui.click(912,968)
    time.sleep(1)
    pyperclip.copy('li')
    time.sleep(1)
    pyautogui.hotkey("ctrl","v")
    time.sleep(1)
    pyautogui.hotkey("enter")
    time.sleep(1)
    pyautogui.moveTo(1302,393)
    time.sleep(1)
    for i in range(1,8):
        pyautogui.scroll(-1)
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/isofoot_model.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/isofoot_model.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
    time.sleep(0.5)
    pyautogui.move(0,30)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/JOUL.jpg', confidence=0.95)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/JOUL.jpg', confidence=0.95-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(0.5)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/RECON.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        time.sleep(1)
        gongs = pyautogui.locateAllOnScreen('E:/park_image/RECON.jpg', confidence=0.99)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(0.5)
    pyautogui.doubleClick(622,154)
    time.sleep(1)
    #텍스트 인식거리 입력
    pyperclip.copy('4000')
    time.sleep(0.5)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('6500')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('50')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(1)
    pyautogui.click(720,262)
    time.sleep(1)
    pyautogui.click(1472,768)
    time.sleep(1)
    time.sleep(0.5)
    pyautogui.hotkey("enter")
    time.sleep(1)

def B1F_SLAB():
    time.sleep(2)
    k = 0
    for i in range(1,30):
        time.sleep(2)
        k += 0.1
        gongs = pyautogui.locateAllOnScreen('E:/park_image/sun.jpg', confidence=0.99-k)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
            break
    time.sleep(1)
    pyautogui.moveTo(1189,418)
    time.sleep(1)
    for i in range(1,8):
        pyautogui.scroll(1)
    time.sleep(1)
    pyautogui.hotkey("esc")
    time.sleep(1)
    pyautogui.click(1240,523)
    time.sleep(1)
    pyautogui.click(1142,542)
    time.sleep(1)
    pyautogui.click(912,968)
    time.sleep(1)
    pyperclip.copy('li')
    time.sleep(1)
    pyautogui.hotkey("ctrl","v")
    time.sleep(1)
    pyautogui.hotkey("enter")
    time.sleep(1)
    pyautogui.moveTo(988,296)
    time.sleep(1)
    for i in range(1,6):
        pyautogui.scroll(-1)
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/slave_model.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        time.sleep(1)
        gongs = pyautogui.locateAllOnScreen('E:/park_image/slave_model.jpg', confidence=0.99)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    #슬라브 면적 라인선택
    pyautogui.click(1141,83)
    time.sleep(1)
    pyautogui.click(430,231)
    time.sleep(1)
    pyautogui.click(1412,780)
    time.sleep(1)
    pyautogui.hotkey("enter")
    time.sleep(3)
    pyautogui.hotkey("esc")
    time.sleep(1)
    # 더미 선택
    gongs = pyautogui.locateAllOnScreen('E:/park_image/PARK_3D.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        time.sleep(1)
        gongs = pyautogui.locateAllOnScreen('E:/park_image/PARK_3D.jpg', confidence=0.99)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(3)
    pyautogui.click(1076,547)
    time.sleep(1)
    pyautogui.scroll(-1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/camera.jpg', confidence=0.85)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    print(gongs_len)
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        time.sleep(1)
        gongs = pyautogui.locateAllOnScreen('E:/park_image/camera.jpg', confidence=0.88)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        print(gongs_len)
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    pyautogui.hotkey("esc")
    time.sleep(1)
    pyautogui.click(1152,524)
    time.sleep(1)
    pyautogui.click(1191,601)
    time.sleep(1)
    pyautogui.click(1302,537)
    time.sleep(1)
    pyautogui.click(1325,628)
    time.sleep(1)
    pyautogui.click(957,463)
    time.sleep(1)
    pyautogui.click(879,444)
    time.sleep(1)
    #더미 체크
    pyautogui.click(290,891)
    time.sleep(1)
    pyautogui.doubleClick(274,775)
    time.sleep(1)
    pyautogui.click(184,799)
    time.sleep(1)
    pyautogui.click(1536,370)
    time.sleep(1)
    pyautogui.hotkey("esc")

def B1F_COLUMN():
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/ROUND.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        time.sleep(1)
        gongs = pyautogui.locateAllOnScreen('E:/park_image/ROUND.jpg', confidence=0.99)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    k = 0
    for i in range(1,30):
        time.sleep(2)
        k += 0.1
        gongs = pyautogui.locateAllOnScreen('E:/park_image/sun.jpg', confidence=0.99-k)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
            break
    time.sleep(1)
    pyautogui.moveTo(850,323)
    time.sleep(1)
    for i in range(1,9):
        pyautogui.scroll(1)
    time.sleep(1)
    pyautogui.click(939,381)
    time.sleep(1)
    pyautogui.click(919,374)
    time.sleep(1)
    pyautogui.click(912,968)
    time.sleep(1)
    pyperclip.copy('li')
    time.sleep(1)
    pyautogui.hotkey("ctrl","v")
    time.sleep(1)
    pyautogui.hotkey("enter")
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/column_model.jpg', confidence=0.99)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        gongs = pyautogui.locateAllOnScreen('E:/park_image/column_model.jpg', confidence=0.98-0.01)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    gongs = pyautogui.locateAllOnScreen('E:/park_image/RECON.jpg', confidence=0.9)
    gongs = list(gongs)
    gongs_len = (len(gongs))
    if gongs_len == 1 :
        pyautogui.moveTo(pyautogui.center(gongs[0]))
        pyautogui.click()
    else :
        time.sleep(1)
        gongs = pyautogui.locateAllOnScreen('E:/park_image/RECON.jpg', confidence=0.99)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
    time.sleep(1)
    time.sleep(0.5)
    pyautogui.doubleClick(622,154)
    time.sleep(1)
    #텍스트 인식거리 입력
    pyperclip.copy('2000')
    time.sleep(0.5)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('2000')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('50')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(1)
    pyautogui.moveTo(1121,266)
    time.sleep(1)
    for i in range(1,10):
        pyautogui.scroll(-1)
    time.sleep(1)
    pyautogui.click(586,240)
    time.sleep(1)
    pyautogui.click(1606,780)
    time.sleep(1)
    pyautogui.hotkey("enter")
    time.sleep(5)

def B1F_WALL():
    time.sleep(2)
    pyautogui.click(928,307)
    time.sleep(1)
    pyautogui.hotkey("esc")
    time.sleep(1)
    k = 0
    for i in range(1,30):
        time.sleep(2)
        k += 0.1
        gongs = pyautogui.locateAllOnScreen('E:/park_image/sun.jpg', confidence=0.99-k)
        gongs = list(gongs)
        gongs_len = (len(gongs))
        if gongs_len == 1 :
            pyautogui.moveTo(pyautogui.center(gongs[0]))
            pyautogui.click()
            break
    time.sleep(1)
    pyautogui.moveTo(1022,229)
    time.sleep(1)
    for i in range(1,10):
        pyautogui.scroll(1)
    time.sleep(1)
    pyautogui.click(975,371)
    time.sleep(1)
    pyautogui.click(966,349)
    time.sleep(1)
    pyautogui.click(912,968)
    time.sleep(1)
    pyperclip.copy('li')
    time.sleep(1)
    pyautogui.hotkey("ctrl","v")
    time.sleep(1)
    pyautogui.hotkey("enter")
    time.sleep(1)
    pyautogui.moveTo(681,303)
    time.sleep(1)
    for i in range(1,9):
        pyautogui.scroll(-1)
    time.sleep(1)
    pyautogui.click(394,261)
    time.sleep(1)
    pyautogui.click(1336,772)
    #텍스트 인식거리 입력
    pyperclip.copy('500')
    time.sleep(0.5)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('300')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(0.5)
    pyautogui.hotkey("tab") 
    time.sleep(0.5)
    pyperclip.copy('50')
    time.sleep(0.3)
    pyautogui.hotkey("ctrl","v")
    time.sleep(1)
    pyautogui.moveTo(1121,266)
    time.sleep(1)
    pyautogui.click(394,261)
    time.sleep(1)
    pyautogui.click(1336,772)
    time.sleep(1)
    pyautogui.hotkey("enter")
    time.sleep(5)




APP()
FLOOR()
MATREIAL()
MATERIAL_IMAGE()
'''
Sectionin_administar_BUTTRESS()
Sectionin_administar_DECKSLAVE()
Sectionin_administar_RWALL()
Sectionin_administar_ISOFOOT()
Sectionin_administar_WALLFOOT()
'''
EXCEL()
DWGRE()
B1F_ISOFOOT()
B1F_WALLFOOT()
B1F_SLAB()
B1F_COLUMN()

#B1F_WALL()



